FROM mcr.microsoft.com/devcontainers/php:1-8.3-bullseye

# PDO/mysqli-Treiber für MariaDB/MySQL nachinstallieren
RUN docker-php-ext-install pdo_mysql mysqli

# Composer ist im Base-Image bereits enthalten
